export const sliderItems = [
  {
    id: 1,
    img: "../images/home/slider1.jpg",
    title: "CASUAL WEAR COLLECTION",
    desc: "Discover trendy casual outfits for women – from everyday dresses to chic tops. Perfect for your daily style upgrade.",
    bg: "f5fafd",
    alt: "Casual wear for women – stylish everyday dresses and tops",
  },
  {
    id: 2,
    img: "../images/home/slider3.jpg",
    title: "FORMAL & OFFICE STYLE",
    desc: "Elegant blouses, dresses, and suits for professional women. Shop the latest office wear and formal fashion trends.",
    bg: "fcf1ed",
    alt: "Formal office wear for women – elegant blouses, dresses, and suits",
  },
  {
    id: 3,
    img: "../images/home/slider2.jpg",
    title: "LOUNGE & COMFY STYLE",
    desc: "Stay stylish at home with our loungewear collection – soft, comfortable, and made for relaxing days in style.",
    bg: "fbf0f4",
    alt: "Loungewear for women – comfortable and stylish home outfits",
  },
];

export const categories = [
  {
    id: 1,
    img: "https://images.pexels.com/photos/5886041/pexels-photo-5886041.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
    title: "SHIRT STYLE!",
    cat: "women",
  },
  {
    id: 2,
    img: "https://images.pexels.com/photos/2983464/pexels-photo-2983464.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
    title: "LOUNGEWEAR LOVE",
    cat: "jeans",
  },
  {
    id: 3,
    img: "https://images.pexels.com/photos/5480696/pexels-photo-5480696.jpeg?auto=compress&cs=tinysrgb&dpr=2&w=500",
    title: "LIGHT JACKETS",
    cat: "coat",
  },
];

export const popularProducts = [
  {
    id: 1,
    img: "../images/products/shirt1.png",
    title: "Vintage Tee",
    category: "shirt",
    color: ["white", "green", "sienna"],
    size: ["M", "L"],
    price: 65,
    oldPrice: 100,
    stock: true,
    sku: "GHT95245AAA",
    tags: ["Women", "Shirt", "Fashion"],
    rating: 4.8,
    desc: "A soft cotton vintage T-shirt for women, made from breathable 100% cotton fabric that feels gentle on the skin. Designed with a timeless vintage look, this tee is versatile enough for everyday wear, whether you're running errands, hanging out with friends, or pairing it with jeans for a casual streetwear style. Its relaxed fit ensures comfort throughout the day while keeping your outfit effortlessly stylish.",
    photos: [
      "../images/products/shirt1_1.png",
      "../images/products/shirt1_2.png",
      "../images/products/shirt1_3.png",
    ],
    reviews: [
      {
        id: 1,
        user: "Kristin Watson",
        date: "1 month ago",
        rating: 5,
        comment: "Love it! The fit and fabric are perfect.",
        images: ["../images/products/shirt1_1.png"],
      },
    ],
  },

  {
    id: 2,
    img: "../images/products/shirt2.png",
    title: "Tied Tee",
    category: "shirt",
    color: ["white", "green", "sienna"],
    size: ["M", "L"],
    price: 55,
    oldPrice: 80,
    stock: true,
    sku: "GHT95245AAA",
    tags: ["Women", "Shirt", "Fashion"],
    rating: 4.9,
    desc: "A trendy tied T-shirt for women crafted from premium cotton for a soft, breathable feel. The stylish front tie detail adds a modern twist to the classic tee, making it perfect for casual outings, coffee dates, or a laid-back weekend look. Pair it with high-waisted jeans, skirts, or shorts for a chic and versatile outfit suitable for summer or spring days.",
    photos: [
      "../images/products/shirt2_1.png",
      "../images/products/shirt2_2.png",
      "../images/products/shirt2_3.png",
    ],
    reviews: [
      {
        id: 1,
        user: "Tya America",
        date: "1 month ago",
        rating: 5,
        comment: "Love it! The fit and fabric are perfect.",
        images: ["../images/products/shirt2_1.png"],
      },
    ],
  },

  // --- Extra Shirt 1 ---
  {
    id: 3,
    img: "../images/products/shirt3.png",
    title: "Oversized Graphic Tee",
    category: "shirt",
    color: ["black", "gray", "navy", "white"],
    size: ["S", "M", "L", "XL"],
    price: 60,
    oldPrice: 75,
    stock: true,
    sku: "SHIRT-OSGT-2025",
    tags: ["Unisex", "Shirt", "Casual"],
    rating: 4.7,
    desc: "This oversized graphic T-shirt is made from a durable cotton blend that combines softness with long-lasting quality. Featuring a bold modern print, it’s designed for those who love relaxed and streetwear-inspired fashion. Perfect for casual hangouts, concerts, or layering under jackets, the oversized fit gives women a comfortable and trendy look.",
    photos: [
      "../images/products/shirt3_1.png",
      "../images/products/shirt3_2.png",
      "../images/products/shirt3_3.png",
    ],
    reviews: [
      {
        id: 1,
        user: "David Lee",
        date: "2 weeks ago",
        rating: 5,
        comment: "Super comfortable and stylish!",
      },
    ],
  },

  // --- Extra Shirt 2 ---
  {
    id: 4,
    img: "../images/products/shirt4.png",
    title: "Striped Linen Shirt",
    category: "shirt",
    color: ["beige", "blue", "white"],
    size: ["M", "L"],
    price: 70,
    oldPrice: 90,
    stock: true,
    sku: "SHIRT-SLN-2025",
    tags: ["Men", "Shirt", "Summer"],
    rating: 4.5,
    desc: "A breathable striped linen shirt designed for men, crafted from lightweight linen fabric that keeps you cool during warm summer days. With its casual yet polished design, this shirt works well for beach vacations, summer parties, or even a relaxed office look. Pair it with shorts for a laid-back vibe or chinos for a smart casual style.",
    photos: [
      "../images/products/shirt4_1.png",
      "../images/products/shirt4_2.png",
      "../images/products/shirt4_3.png",
    ],
    reviews: [
      {
        id: 1,
        user: "Anna Smith",
        date: "3 days ago",
        rating: 4,
        comment: "Great quality but runs slightly large.",
      },
    ],
  },

  // --- Dress 1 ---
  {
    id: 5,
    img: "../images/products/dress1.png",
    title: "Floral Summer Dress",
    category: "dress",
    color: ["yellow", "pink", "white"],
    size: ["S", "M", "L"],
    price: 85,
    oldPrice: 120,
    stock: true,
    sku: "DRS-FLR-2025",
    tags: ["Women", "Dress", "Summer"],
    rating: 4.8,
    desc: "A lightweight floral summer dress made from soft, flowy fabric that allows maximum comfort while keeping you stylish in warm weather. Its vibrant floral pattern brings a cheerful vibe, perfect for brunch dates, garden parties, or holiday getaways. Designed with a flattering fit, this dress can be styled with sandals for a relaxed look or heels for a more elegant appearance.",
    photos: [
      "../images/products/dress1_1.png",
      "../images/products/dress1_2.png",
      "../images/products/dress1_3.png",
    ],
    reviews: [
      {
        id: 1,
        user: "Cindy Lau",
        date: "1 week ago",
        rating: 5,
        comment: "Love this dress! Perfect for brunch dates.",
        images: [
          "../images/products/dress1_2.png",
          "../images/products/dress1_3.png",
        ],
      },
    ],
  },

  // --- Dress 2 ---
  {
    id: 6,
    img: "../images/products/dress2.png",
    title: "Elegant Evening Dress",
    category: "dress",
    color: ["red", "black"],
    size: ["S", "M"],
    price: 150,
    oldPrice: 200,
    stock: true,
    sku: "DRS-EVD-2025",
    tags: ["Women", "Dress", "Formal"],
    rating: 4.9,
    desc: "An elegant long evening dress tailored from premium satin-blend fabric, giving it a luxurious sheen and flow. Designed for special occasions like weddings, galas, or formal dinners, this dress hugs the body beautifully while allowing ease of movement. Available in classic colors such as red and black, it’s the perfect statement piece for women who want to stand out with timeless sophistication.",
    photos: [
      "../images/products/dress2_1.png",
      "../images/products/dress2_2.png",
      "../images/products/dress2_3.png",
    ],
    reviews: [
      {
        id: 1,
        user: "Michelle Tan",
        date: "2 months ago",
        rating: 5,
        comment: "Stunning dress, feels luxurious!",
      },
    ],
  },

  // --- sweat ---
  {
    id: 7,
    img: "../images/products/sweat1.png",
    title: "Cozy Knit sweat",
    category: "sweat",
    color: ["cream", "brown", "gray"],
    size: ["M", "L", "XL"],
    price: 95,
    oldPrice: 130,
    stock: true,
    sku: "SWT-KNT-2025",
    tags: ["Unisex", "sweat", "Winter"],
    rating: 4.6,
    desc: "Warm and cozy knitted sweat for cold seasons.",
    photos: [
      "../images/products/sweat1_1.png",
      "../images/products/sweat1_2.png",
      "../images/products/sweat1_3.png",
    ],
    reviews: [
      {
        id: 1,
        user: "James Park",
        date: "5 days ago",
        rating: 4,
        comment: "Very comfy, but a little bulky.",
      },
    ],
  },

  // --- Dress 3 ---
  {
    id: 8,
    img: "../images/products/dress3.png",
    title: "Casual Midi Dress",
    category: "dress",
    color: ["olive", "navy", "white"],
    size: ["S", "M", "L"],
    price: 78,
    oldPrice: 110,
    stock: true,
    sku: "DRS-MIDI-2025",
    tags: ["Women", "Dress", "Casual"],
    rating: 4.7,
    desc: "Comfortable midi dress perfect for everyday wear.",
    photos: [
      "../images/products/dress3_1.png",
      "../images/products/dress3_2.png",
    ],
    reviews: [
      {
        id: 1,
        user: "Lina Hart",
        date: "2 weeks ago",
        rating: 5,
        comment: "Love how comfy it feels!",
      },
    ],
  },

  // --- Dress 4 ---
  {
    id: 9,
    img: "../images/products/dress4.png",
    title: "Party Sequin Dress",
    category: "dress",
    color: ["black", "silver", "gold"],
    size: ["S", "M"],
    price: 165,
    oldPrice: 210,
    stock: true,
    sku: "DRS-SEQ-2025",
    tags: ["Women", "Dress", "Party"],
    rating: 4.8,
    desc: "Sparkly sequin dress to shine at every party.",
    photos: [
      "../images/products/dress4_1.png",
      "../images/products/dress4_2.png",
      "../images/products/dress4_3.png",
    ],
    reviews: [
      {
        id: 1,
        user: "Sarah J.",
        date: "3 days ago",
        rating: 5,
        comment: "Wore it to a party, got so many compliments!",
      },
      {
        id: 2,
        user: "Emily Rose",
        date: "1 week ago",
        rating: 4,
        comment: "Super sparkly! A bit heavy but looks amazing.",
      },
      {
        id: 3,
        user: "Cindy Wu",
        date: "2 weeks ago",
        rating: 5,
        comment: "My favorite dress now, fits perfectly!",
      },
    ],
  },

  // --- Dress 5 ---
  {
    id: 10,
    img: "../images/products/dress6.png",
    title: "Summer Garden Dress",
    category: "dress",
    color: ["cream", "brown", "orange", "blue"],
    size: ["M", "L"],
    price: 120,
    oldPrice: 160,
    stock: true,
    sku: "DRS-BOHO-2025",
    tags: ["Women", "Dress"],
    rating: 4.6,
    desc: "Summer perfect dress, flowy and comfortable.",
    photos: [
      "../images/products/dress6_1.png",
      "../images/products/dress6_2.png",
      "../images/products/dress6_3.png",
    ],
    reviews: [
      {
        id: 1,
        user: "Nadia Rahman",
        date: "1 month ago",
        rating: 4,
        comment: "Beautiful design, fabric could be softer.",
      },
    ],
  },

  // --- Hoodie (jacket1) ---
  {
    id: 11,
    img: "../images/products/jacket1.png",
    title: "Classic Hoodie",
    category: "hoodie",
    color: ["black", "gray", "navy", "red"],
    size: ["M", "L", "XL"],
    price: 85,
    oldPrice: 120,
    stock: true,
    sku: "HD-CLS-2025",
    tags: ["Unisex", "Hoodie", "Streetwear"],
    rating: 4.7,
    desc: "Everyday hoodie with a relaxed fit and soft fleece lining.",
    photos: [
      "../images/products/jacket1_1.png",
      "../images/products/jacket1_2.png",
      "../images/products/jacket1-3.png",
    ],
    reviews: [
      {
        id: 1,
        user: "Kevin Lau",
        date: "5 days ago",
        rating: 5,
        comment: "Super cozy and stylish, I wear it almost every day!",
      },
      {
        id: 2,
        user: "Amanda Green",
        date: "1 month ago",
        rating: 4,
        comment: "Great hoodie but wish the hood was a bit larger.",
      },
    ],
  },

  // --- Extra Shirt 3 ---
  {
    id: 12,
    img: "../images/products/shirt5.png",
    title: "Pattern Based Shirt",
    category: "shirt",
    color: ["red", "blue", "green"],
    size: ["M", "L", "XL"],
    price: 65,
    oldPrice: 95,
    stock: true,
    sku: "SHIRT-PLD-2025",
    tags: ["Unisex", "Shirt", "Winter"],
    rating: 4.5,
    desc: "Soft plaid flannel shirt, great for layering in cooler weather.",
    photos: [
      "../images/products/shirt5_1.png",
      "../images/products/shirt5_2.png",
    ],
    reviews: [
      {
        id: 1,
        user: "Daniel Kim",
        date: "2 weeks ago",
        rating: 4,
        comment: "Good quality, a little thicker than expected.",
      },
    ],
  },
];
